// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xDMZjnNSn3v3bMGOygQFUHEC3Lk7nk8',
    appId: '1:1015460904025:web:32275dbac20a85bf864548',
    messagingSenderId: '1015460904025',
    projectId: 'chatur-689f5',
    authDomain: 'chatur-689f5.firebaseapp.com',
    storageBucket: 'chatur-689f5.firebasestorage.app',
    measurementId: 'G-RDPPGGTNFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXBR_3g8h4JmgAPZaUFNXEjKZCOltbAwM',
    appId: '1:1015460904025:android:3de57ee3136ebb85864548',
    messagingSenderId: '1015460904025',
    projectId: 'chatur-689f5',
    storageBucket: 'chatur-689f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC84HspYznGgPiUqgHaSop0xFxNoPh71i8',
    appId: '1:1015460904025:ios:342262cb43b12ac1864548',
    messagingSenderId: '1015460904025',
    projectId: 'chatur-689f5',
    storageBucket: 'chatur-689f5.firebasestorage.app',
    androidClientId: '1015460904025-ega3erj4dlu3eoif41ivsn87ob30uf1o.apps.googleusercontent.com',
    iosClientId: '1015460904025-ge7cp6p1pq5dthr9rimpvuiluures279.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaturFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC84HspYznGgPiUqgHaSop0xFxNoPh71i8',
    appId: '1:1015460904025:ios:342262cb43b12ac1864548',
    messagingSenderId: '1015460904025',
    projectId: 'chatur-689f5',
    storageBucket: 'chatur-689f5.firebasestorage.app',
    androidClientId: '1015460904025-ega3erj4dlu3eoif41ivsn87ob30uf1o.apps.googleusercontent.com',
    iosClientId: '1015460904025-ge7cp6p1pq5dthr9rimpvuiluures279.apps.googleusercontent.com',
    iosBundleId: 'com.example.chaturFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1xDMZjnNSn3v3bMGOygQFUHEC3Lk7nk8',
    appId: '1:1015460904025:web:cfe1dd989d274df2864548',
    messagingSenderId: '1015460904025',
    projectId: 'chatur-689f5',
    authDomain: 'chatur-689f5.firebaseapp.com',
    storageBucket: 'chatur-689f5.firebasestorage.app',
    measurementId: 'G-WHYM44MKDQ',
  );

}